"""initial schema (05 Backend Schema v1.0)

Revision ID: 0001
Revises: 
Create Date: 2026-10-01 21:15:58.592374
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datasets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('filter_spec', sa.Text(), nullable=False),
    sa.Column('split_spec', sa.Text(), nullable=False),
    sa.Column('test_set_name', sa.Text(), nullable=False),
    sa.Column('normalizer_version', sa.Text(), nullable=False),
    sa.Column('sha256', sa.Text(), nullable=True),
    sa.Column('frozen', sa.Integer(), nullable=False),
    sa.Column('export_path', sa.Text(), nullable=True),
    sa.Column('stats', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.CheckConstraint('frozen IN (0, 1)', name='ck_frozen'),
    sa.CheckConstraint('json_valid(filter_spec)', name='ck_filter_spec_json'),
    sa.CheckConstraint('json_valid(split_spec)', name='ck_split_spec_json'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Text(), nullable=True),
    sa.Column('heartbeat_at', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('started_at', sa.Text(), nullable=True),
    sa.Column('finished_at', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.CheckConstraint("kind IN ('parse_transcript', 'align', 'vad_segment', 'hypothesize', 'build_dataset', 'export_dataset', 'register_model', 'convert_model', 'evaluate', 'transcribe', 'export_transcription')", name='ck_kind'),
    sa.CheckConstraint("status IN ('queued', 'running', 'done', 'failed', 'cancelled')", name='ck_status'),
    sa.CheckConstraint('json_valid(payload)', name='ck_payload_json'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index('ix_jobs_queue', ['status', 'created_at'], unique=False)

    op.create_table('recordings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('original_path', sa.Text(), nullable=False),
    sa.Column('normalized_path', sa.Text(), nullable=True),
    sa.Column('sha256', sa.Text(), nullable=False),
    sa.Column('duration_s', sa.Float(), nullable=False),
    sa.Column('domain', sa.Text(), nullable=False),
    sa.Column('consent_scope', sa.Text(), nullable=False),
    sa.Column('recorded_on', sa.Text(), nullable=True),
    sa.Column('region', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.CheckConstraint("consent_scope IN ('training', 'eval_only', 'transcription_only')", name='ck_consent'),
    sa.CheckConstraint("domain IN ('interview', 'tv', 'radio', 'church', 'meeting', 'other')", name='ck_domain'),
    sa.CheckConstraint("status IN ('imported', 'aligning', 'ready_for_review', 'alignment_suspect', 'reviewed', 'archived')", name='ck_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sha256')
    )
    op.create_table('source_transcripts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('recording_id', sa.String(), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('format', sa.Text(), nullable=False),
    sa.Column('sha256', sa.Text(), nullable=False),
    sa.Column('parser', sa.Text(), nullable=False),
    sa.Column('parser_version', sa.Text(), nullable=False),
    sa.Column('italic_means', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.CheckConstraint("format IN ('docx', 'pdf', 'txt')", name='ck_format'),
    sa.CheckConstraint("italic_means IN ('sw', 'en', 'none')", name='ck_italic'),
    sa.ForeignKeyConstraint(['recording_id'], ['recordings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recording_id', 'sha256')
    )
    op.create_table('test_set_recordings',
    sa.Column('test_set_name', sa.Text(), nullable=False),
    sa.Column('recording_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['recording_id'], ['recordings.id'], ),
    sa.PrimaryKeyConstraint('test_set_name', 'recording_id')
    )
    op.create_table('training_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('dataset_id', sa.String(), nullable=False),
    sa.Column('base_model', sa.Text(), nullable=False),
    sa.Column('platform', sa.Text(), nullable=False),
    sa.Column('config', sa.Text(), nullable=False),
    sa.Column('code_commit', sa.Text(), nullable=True),
    sa.Column('notebook_ref', sa.Text(), nullable=True),
    sa.Column('dev_metrics', sa.Text(), nullable=True),
    sa.Column('started_at', sa.Text(), nullable=True),
    sa.Column('finished_at', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.CheckConstraint("platform IN ('kaggle', 'local', 'other')", name='ck_platform'),
    sa.CheckConstraint("status IN ('registered', 'failed')", name='ck_status'),
    sa.CheckConstraint('json_valid(config)', name='ck_config_json'),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alignment_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('recording_id', sa.String(), nullable=False),
    sa.Column('source_transcript_id', sa.String(), nullable=False),
    sa.Column('aligner', sa.Text(), nullable=False),
    sa.Column('aligner_version', sa.Text(), nullable=False),
    sa.Column('params', sa.Text(), nullable=False),
    sa.Column('mean_confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('finished_at', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.CheckConstraint("status IN ('running', 'done', 'failed')", name='ck_status'),
    sa.CheckConstraint('json_valid(params)', name='ck_params_json'),
    sa.ForeignKeyConstraint(['recording_id'], ['recordings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_transcript_id'], ['source_transcripts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_versions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('family', sa.Text(), nullable=False),
    sa.Column('base_model', sa.Text(), nullable=False),
    sa.Column('training_run_id', sa.String(), nullable=True),
    sa.Column('hf_path', sa.Text(), nullable=False),
    sa.Column('ct2_path', sa.Text(), nullable=True),
    sa.Column('decode_params', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('promoted_at', sa.Text(), nullable=True),
    sa.Column('promotion_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.CheckConstraint("family IN ('whisper', 'w2vbert_ctc', 'legacy_ctc')", name='ck_family'),
    sa.CheckConstraint("status IN ('converting', 'candidate', 'production', 'retired', 'broken')", name='ck_status'),
    sa.CheckConstraint('json_valid(decode_params)', name='ck_decode_params_json'),
    sa.ForeignKeyConstraint(['training_run_id'], ['training_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('model_versions', schema=None) as batch_op:
        batch_op.create_index('ux_one_production', ['status'], unique=True, sqlite_where=sa.text("status = 'production'"), postgresql_where=sa.text("status = 'production'"))

    op.create_table('transcript_turns',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source_transcript_id', sa.String(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('speaker_label', sa.Text(), nullable=True),
    sa.Column('speaker_role', sa.Text(), nullable=True),
    sa.Column('text_raw', sa.Text(), nullable=False),
    sa.Column('text_align', sa.Text(), nullable=False),
    sa.Column('word_map', sa.Text(), nullable=False),
    sa.Column('spans', sa.Text(), nullable=False),
    sa.Column('annotations', sa.Text(), nullable=False),
    sa.CheckConstraint("speaker_role IN ('interviewer', 'respondent', 'host', 'preacher', 'audience', 'other')", name='ck_role'),
    sa.CheckConstraint('json_valid(annotations)', name='ck_annotations_json'),
    sa.CheckConstraint('json_valid(spans)', name='ck_spans_json'),
    sa.CheckConstraint('json_valid(word_map)', name='ck_word_map_json'),
    sa.ForeignKeyConstraint(['source_transcript_id'], ['source_transcripts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_transcript_id', 'ordinal')
    )
    op.create_table('aligned_words',
    sa.Column('alignment_run_id', sa.String(), nullable=False),
    sa.Column('turn_id', sa.String(), nullable=False),
    sa.Column('word_idx', sa.Integer(), nullable=False),
    sa.Column('word', sa.Text(), nullable=False),
    sa.Column('start_s', sa.Float(), nullable=False),
    sa.Column('end_s', sa.Float(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['alignment_run_id'], ['alignment_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['turn_id'], ['transcript_turns.id'], ),
    sa.PrimaryKeyConstraint('alignment_run_id', 'turn_id', 'word_idx')
    )
    op.create_table('eval_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('model_version_id', sa.String(), nullable=False),
    sa.Column('dataset_id', sa.String(), nullable=False),
    sa.Column('split', sa.Text(), nullable=False),
    sa.Column('normalizer_version', sa.Text(), nullable=False),
    sa.Column('metrics', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.CheckConstraint("split IN ('dev', 'test', 'external')", name='ck_split'),
    sa.CheckConstraint("status IN ('queued', 'running', 'done', 'failed')", name='ck_status'),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('segments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('recording_id', sa.String(), nullable=False),
    sa.Column('alignment_run_id', sa.String(), nullable=True),
    sa.Column('origin', sa.Text(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('start_s', sa.Float(), nullable=False),
    sa.Column('end_s', sa.Float(), nullable=False),
    sa.Column('speaker_label', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('current_revision_id', sa.String(), nullable=True),
    sa.Column('alignment_conf', sa.Float(), nullable=True),
    sa.Column('auto_flags', sa.Text(), nullable=False),
    sa.Column('priority', sa.Float(), nullable=False),
    sa.Column('audio_cache_path', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.CheckConstraint("origin IN ('alignment', 'vad', 'inference_correction')", name='ck_origin'),
    sa.CheckConstraint("status IN ('candidate', 'in_review', 'draft', 'approved', 'approved_eval_only', 'rejected')", name='ck_status'),
    sa.CheckConstraint('end_s > start_s', name='ck_bounds'),
    sa.CheckConstraint('json_valid(auto_flags)', name='ck_auto_flags_json'),
    sa.ForeignKeyConstraint(['alignment_run_id'], ['alignment_runs.id'], ),
    sa.ForeignKeyConstraint(['current_revision_id'], ['segment_revisions.id'], name='fk_segments_current_revision', use_alter=True),
    sa.ForeignKeyConstraint(['recording_id'], ['recordings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recording_id', 'ordinal')
    )
    op.create_table('transcriptions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('input_path', sa.Text(), nullable=False),
    sa.Column('sha256', sa.Text(), nullable=False),
    sa.Column('duration_s', sa.Float(), nullable=True),
    sa.Column('domain', sa.Text(), nullable=False),
    sa.Column('consent_to_train', sa.Integer(), nullable=False),
    sa.Column('model_version_id', sa.String(), nullable=False),
    sa.Column('rtf', sa.Float(), nullable=True),
    sa.Column('expires_at', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.CheckConstraint('consent_to_train IN (0, 1)', name='ck_consent'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eval_results',
    sa.Column('eval_run_id', sa.String(), nullable=False),
    sa.Column('segment_id', sa.String(), nullable=False),
    sa.Column('reference', sa.Text(), nullable=False),
    sa.Column('hypothesis', sa.Text(), nullable=False),
    sa.Column('wer', sa.Float(), nullable=False),
    sa.Column('cer', sa.Float(), nullable=False),
    sa.Column('n_ref_words', sa.Integer(), nullable=False),
    sa.Column('n_switch_points', sa.Integer(), nullable=False),
    sa.Column('n_switch_errors', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['eval_run_id'], ['eval_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.id'], ),
    sa.PrimaryKeyConstraint('eval_run_id', 'segment_id')
    )
    op.create_table('hypotheses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('segment_id', sa.String(), nullable=False),
    sa.Column('model_version_id', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('words', sa.Text(), nullable=True),
    sa.Column('avg_logprob', sa.Float(), nullable=True),
    sa.Column('no_speech_prob', sa.Float(), nullable=True),
    sa.Column('wer_vs_current', sa.Float(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.CheckConstraint('words IS NULL OR json_valid(words)', name='ck_words_json'),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('segment_turns',
    sa.Column('segment_id', sa.String(), nullable=False),
    sa.Column('turn_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['turn_id'], ['transcript_turns.id'], ),
    sa.PrimaryKeyConstraint('segment_id', 'turn_id')
    )
    op.create_table('transcription_segments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('transcription_id', sa.String(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('start_s', sa.Float(), nullable=False),
    sa.Column('end_s', sa.Float(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('words', sa.Text(), nullable=True),
    sa.Column('avg_logprob', sa.Float(), nullable=True),
    sa.Column('no_speech_prob', sa.Float(), nullable=True),
    sa.Column('edited_text', sa.Text(), nullable=True),
    sa.Column('edited_at', sa.Text(), nullable=True),
    sa.Column('promoted_segment_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['promoted_segment_id'], ['segments.id'], ),
    sa.ForeignKeyConstraint(['transcription_id'], ['transcriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transcription_id', 'ordinal')
    )
    op.create_table('segment_revisions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('segment_id', sa.String(), nullable=False),
    sa.Column('revision_no', sa.Integer(), nullable=False),
    sa.Column('parent_revision_id', sa.String(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('start_s', sa.Float(), nullable=False),
    sa.Column('end_s', sa.Float(), nullable=False),
    sa.Column('speaker_label', sa.Text(), nullable=True),
    sa.Column('flags', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('hypothesis_id', sa.String(), nullable=True),
    sa.Column('author', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.CheckConstraint("source IN ('aligned_transcript', 'vad_empty', 'model_hypothesis', 'human')", name='ck_source'),
    sa.CheckConstraint("status IN ('candidate', 'in_review', 'draft', 'approved', 'approved_eval_only', 'rejected')", name='ck_status'),
    sa.CheckConstraint('json_valid(flags)', name='ck_flags_json'),
    sa.ForeignKeyConstraint(['hypothesis_id'], ['hypotheses.id'], ),
    sa.ForeignKeyConstraint(['parent_revision_id'], ['segment_revisions.id'], ),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('segment_id', 'revision_no')
    )
    op.create_table('dataset_items',
    sa.Column('dataset_id', sa.String(), nullable=False),
    sa.Column('segment_id', sa.String(), nullable=False),
    sa.Column('revision_id', sa.String(), nullable=False),
    sa.Column('split', sa.Text(), nullable=False),
    sa.CheckConstraint("split IN ('train', 'dev', 'test')", name='ck_split'),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['revision_id'], ['segment_revisions.id'], ),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.id'], ),
    sa.PrimaryKeyConstraint('dataset_id', 'segment_id')
    )
    with op.batch_alter_table('dataset_items', schema=None) as batch_op:
        batch_op.create_index('ix_dataset_items_split', ['dataset_id', 'split'], unique=False)

    op.create_table('language_spans',
    sa.Column('revision_id', sa.String(), nullable=False),
    sa.Column('char_start', sa.Integer(), nullable=False),
    sa.Column('char_end', sa.Integer(), nullable=False),
    sa.Column('lang', sa.Text(), nullable=False),
    sa.CheckConstraint("lang IN ('en', 'sw', 'mixed', 'luo', 'other', 'unclear')", name='ck_lang'),
    sa.CheckConstraint('char_end > char_start', name='ck_span'),
    sa.ForeignKeyConstraint(['revision_id'], ['segment_revisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('revision_id', 'char_start')
    )
    # Expression index (autogenerate cannot reflect these on SQLite).
    op.create_index('ix_segments_queue', 'segments', ['recording_id', 'status', sa.text('priority DESC')])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_segments_queue', table_name='segments')
    op.drop_table('language_spans')
    with op.batch_alter_table('dataset_items', schema=None) as batch_op:
        batch_op.drop_index('ix_dataset_items_split')

    op.drop_table('dataset_items')
    op.drop_table('segment_revisions')
    op.drop_table('transcription_segments')
    op.drop_table('segment_turns')
    op.drop_table('hypotheses')
    op.drop_table('eval_results')
    op.drop_table('transcriptions')
    op.drop_table('segments')
    op.drop_table('eval_runs')
    op.drop_table('aligned_words')
    op.drop_table('transcript_turns')
    with op.batch_alter_table('model_versions', schema=None) as batch_op:
        batch_op.drop_index('ux_one_production', sqlite_where=sa.text("status = 'production'"), postgresql_where=sa.text("status = 'production'"))

    op.drop_table('model_versions')
    op.drop_table('alignment_runs')
    op.drop_table('training_runs')
    op.drop_table('test_set_recordings')
    op.drop_table('source_transcripts')
    op.drop_table('recordings')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_jobs_queue')

    op.drop_table('jobs')
    op.drop_table('datasets')
    # ### end Alembic commands ###
